vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:  
                    service: App\Vich\EntityDirectoryNamer   
            delete_on_remove: true
            delete_on_update: true
